version: '3.8'

services:
  sim-portfolio:
    build: .
    container_name: sim-portfolio
    environment:
      - TZ=Asia/Taipei
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8897:8897"
    restart: unless-stopped
    networks:
      - infra-network
      - shioaji-network
      - ibapi-trading_default

networks:
  infra-network:
    external: true
  shioaji-network:
    external: true
  ibapi-trading_default:
    external: true
